# Generated by Django 4.1.7 on 2023-03-20 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0.0)),
                ('tag', models.CharField(choices=[('dining', 'Dining'), ('travel', 'Travel'), ('stay', 'Stay'), ('adventure', 'Adventure'), ('shopping', 'Shopping'), ('others', 'Others')], default='others', max_length=10)),
                ('number_of_debtors', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail', models.CharField(max_length=250)),
                ('first_nam', models.CharField(max_length=250)),
                ('last_name', models.CharField(blank=True, max_length=250)),
                ('profile', models.ImageField(default='profile.jfif', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SplitDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('debtor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetPlanner.user')),
                ('split_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetPlanner.split')),
            ],
        ),
        migrations.AddField(
            model_name='split',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetPlanner.user'),
        ),
    ]
