# Generated by Django 4.1.7 on 2023-03-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetPlanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='split',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='splitdistribution',
            old_name='debtor_id',
            new_name='debtor',
        ),
        migrations.RenameField(
            model_name='splitdistribution',
            old_name='split_id',
            new_name='split',
        ),
    ]
