# Generated by Django 4.1.7 on 2023-03-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetPlanner', '0002_rename_owner_id_split_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_nam',
            new_name='first_name',
        ),
    ]
