# Generated by Django 4.1.7 on 2023-03-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetPlanner', '0006_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
