# Generated by Django 4.1.7 on 2023-03-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetPlanner', '0007_alter_split_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitdistribution',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
