# Generated by Django 4.1.7 on 2023-04-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_event_planner_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planner',
            old_name='location',
            new_name='loc',
        ),
    ]
