# Generated by Django 4.1.7 on 2023-04-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='url',
            new_name='src',
        ),
    ]
